version: '3.3'

networks:
  mysql-network:

services:
  #service 1: definition of mysql database
  mysql-db:
    image: mysql:5.7-oracle
    container_name: mysql-5.7-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    restart: always

  #service 2: definition of your spring-boot app
  aspaservice:                        #it is just a name, which will be used only in this file.
    image: aspa-api-image               #name of the image after dockerfile executes (if you have a build step where you build the image, otherwise name of the image to pull)
    container_name: aspa-api-container  #name of the container created from docker image
    #build:
    #  context: .                          #docker file path (. means root directory)
    #  dockerfile: Dockerfile              #docker file name
    ports:
      - "8443:8443"                       #docker container port with your os port
    networks:
      - mysql-network
    restart: always

    depends_on:                           #define dependencies of this app
      - mysql-db                          #dependency name (which is defined with this name 'mysql-db' in this file earlier)
    #variables de entorno (también se podrían especificar en el Dockerfile):
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-5.7-container:3306/database-name?serverTimezone=UTC&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SSL-CERT-PATH: /ssl/live/domain-name/cert.pem
      SSL-CERT-PRIVATE-KEY-PATH: /ssl/live/domain-name/privkey.pem
    volumes:
      - /etc/letsencrypt/:/ssl #ruta de los certificados ssl que utiliza la aplicación, se monta el directorio /etc/letsencrypt del servidor en el /ssl del contenedor
